# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0002_auto_20161021_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travelers', models.ManyToManyField(related_name='trips', to='login_reg_app.User')),
                ('trip_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='login_reg_app.User')),
            ],
        ),
    ]
