# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.TextField(default='sightseeing'),
            preserve_default=False,
        ),
    ]
